version: "3.9"

networks:
  votacao-network:
    driver: bridge

services:
  votacao-postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=votacao
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - votacao-network

  votacao-postgres-test:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=votacao_test
    ports:
      - "5433:5432"
    volumes:
    - ./create_votacao_db.sql:/docker-entrypoint-initdb.d/create_votacao_db.sql
    networks:
      - votacao-network


  votacao:
    build: ./
    environment:
      DB_HOST: votacao-postgres
      DB_TEST_HOST: votacao-postgres-test
    ports:
      - "8080:8080"
    networks:
      - votacao-network
    depends_on:
      - votacao-postgres