version: "3.9"

networks:
  votacao-network:
    driver: bridge

services:
  votacao-postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=votacao
    ports:
      - "15432:5432"
    volumes:
      - ./volume-postgres:/var/lib/postgresql/data
    networks:
      - votacao-network
      
  votacao-postgres-test:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=votacao_test
    volumes:
        - ./create_votacao_db_test.sh:/docker-entrypoint-initdb.d/create_votacao_db_test.sh
    ports:
      - "15433:5432"
    networks:
      - votacao-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "lucas@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "61886:80"
    depends_on:
      - votacao-postgres
    networks:
      - votacao-network

  votacao:
    build: ./
    environment:
      DB_HOST: votacao-postgres
    ports:
      - "8080:8080"
    networks:
      - votacao-network
    depends_on:
      - votacao-postgres